### ISSUE TITLE
update people page

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/comcast.github.io#6]
add latest talk links like Shilla @ ASF, Shilla @ KubeCon EU 
keynotes and topic talks can be merged into one category
talks should be sorted automatically by date
this is the page that needs to be updated: https://comcast.github.io/comcast.github.io-website/people

**Comment by shillasaebi** [comment]
February 25 2021 
GitHub InFocus event - Modernizing and unifying development at Comcast with Martin Woodward and Brittany Istenes
https://www.youtube.com/watch?v=jp2S1hLn6zE

March 19 2021 
30 Years of Linux and Open Source: Fireside Chat with Nithya Ruff
https://www.youtube.com/watch?v=47Afpkg8sj8

March 24 2021
Academy Software Foundation: Fireside Chat on Open Source Program Offices (OSPO) - Shilla Saebi, Nigel Simpson, John Mertic
https://www.youtube.com/watch?v=mPRoMwDjT1Y

May 5, 2021
KubeCon EU: Building Your Brand with CNCF - Shilla Saebi, Bill Mulligan
https://static.sched.com/hosted_files/kccnceu2021/e3/Building%20your%20Brand%20with%20CNCF%20KubeCon%20EU%202021.pdf

**Comment by BrittanyIstenes** [comment]
I scanned the editorial calendar, all past calendar events from this year and my saved spreadsheet.  All are up to date.  I think you are safe for update then PR reivew

**Comment by shillasaebi** [comment]
this is complete. Here is the PR: https://github.com/Comcast/comcast.github.io-website/pull/22
