### ISSUE TITLE
Link OpenSSF announcement to blog page

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/comcast.github.io#69]
The OpenSSF announcement/article should be posted on the blog page under the “IN AND AROUND THE WEB” section here: https://comcast.github.io/blog

Date of article: May 9, 2022

Title: OpenSSF Announces 15 New Members To Further Strengthen Open Source Software Supply Chain Security

Link to article: https://openssf.org/press-release/2022/05/09/openssf-announces-15-new-members-to-further-strengthen-open-source-software-supply-chain-security/

**Comment by olukowski** [comment]
Can I do this?

**Comment by KlayD51** [comment]
Hi, don't do this one please.  I'm an intern with the OSPO and will be working on this issue soon, thank you.

**Comment by o2ku** [comment]
where can i go to do my twilioquset mission?

**Comment by shillasaebi** [comment]
@o2ku can you please elaborate on the twilioquset mission? I'm not sure what that relates to. Thank you!
